# escape=`
FROM microsoft/dotnet-framework-build:4.7.1-windowsservercore-ltsc2016 AS builder
WORKDIR C:\src\Legacy.CloudService
COPY . .
RUN msbuild src\Legacy.CloudService.sln /p:OutputPath=c:\out

# app image
FROM microsoft/dotnet-framework:4.7.1-windowsservercore-10.0.14393.1884
ADD .\setup C:\setup
RUN C:\setup\install.cmd
WORKDIR C:\legacy-cloudservice
COPY --from=builder C:\out .
CMD Console.Worker.Role.exe